#!/bin/sh

# PROVIDE: PuchCoin
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# PuchCoin_enable (bool): Set to NO by default. Set this variable to YES if you want to enable PuchCoin service.
# PuchCoin_config (path): Set to /usr/local/etc/PuchCoin.conf by default.
# PuchCoin_user:  The user account PuchCoin daemon runs as. It uses 'root' user by default.
# PuchCoin_group: The group account PuchCoin daemon runs as. It uses 'wheel' group by default.
# PuchCoin_datadir (str): Default to "/var/db/PuchCoin". Base data directory.

. /etc/rc.subr

name=PuchCoin
rcvar=PuchCoin_enable

: ${PuchCoin_enable:=NO}
: ${PuchCoin_config=/usr/local/etc/PuchCoin.conf}
: ${PuchCoin_datadir=/var/db/PuchCoin}
: ${PuchCoin_user="root"}
: ${PuchCoin_group="wheel"}

required_files=${PuchCoin_config}
command=/usr/local/bin/PuchCoind
PuchCoin_chdir=${PuchCoin_datadir}
pidfile="${PuchCoin_datadir}/PuchCoind.pid"
stop_cmd=PuchCoin_stop
command_args="-conf=${PuchCoin_config} -datadir=${PuchCoin_datadir} -daemon -pid=${pidfile}"
start_precmd="${name}_prestart"

PuchCoin_create_datadir()
{
	echo "Creating data directory"
	eval mkdir -p ${PuchCoin_datadir}
	[ $? -eq 0 ] && chown -R ${PuchCoin_user}:${PuchCoin_group} ${PuchCoin_datadir}
}

PuchCoin_prestart()
{
	if [ ! -d "${PuchCoin_datadir}/." ]; then
		PuchCoin_create_datadir || return 1
	fi
}

PuchCoin_requirepidfile()
{
	if [ ! "0`check_pidfile ${pidfile} ${command}`" -gt 1 ]; then
		echo "${name} not running? (check $pidfile)."
		exit 1
	fi
}

PuchCoin_stop()
{
    PuchCoin_requirepidfile

	echo "Stopping ${name}."
	eval ${command} -conf=${PuchCoin_config} -datadir=${PuchCoin_datadir} stop
	wait_for_pids ${rc_pid}
}

load_rc_config $name
run_rc_command "$1"
